### ISSUE TITLE
"/?" not recognized as a parameter.

### ISSUE THREAD

**Issue by zxz41** [PotcFdk/chatsounds-preprocessor#3]
```
>help chatsounds-preprocessor
This command is not supported by the help utility.  Try "chatsounds-preprocessor
 /?".

etc etc

Unknown command line parameter: /?
```
/? should probably refer to help too, just for measure.

**Comment by SpiralP** [comment]
I think it wants you to run the program itself, not help, like `>chatsounds-preprocessor /?`
on my side it then tells you `Unknown command line parameter: /?
For usage help, see -h or --help.`
and finally, running with -h/--help gives the correct usage options

**Comment by SpiralP** [comment]
ah you want it alongside with --help nvm
