### ISSUE TITLE
"Beautiful" listing

### ISSUE THREAD

**Issue by zxz41** [PotcFdk/chatsounds-preprocessor#4]
## It would be really handy with a parameter (-b, --beautiful) for generating nicer looking listings.

Beautiful listing:
```
c.StartList("sample")
	L["sound"] = {
		{
			path = "chatsounds/autoadd/sample/sound.ogg",
			length = 3.141592653589793,
		},
	}
c.EndList()
```

**NOT** Beautiful listing:
```
c.StartList("sample")
L["sound"]={{path="chatsounds/autoadd/sample/sound.ogg",length=3.141592653589793}}
c.EndList()
```

**Comment by PotcFdk** [comment]
Is there any reason why this is required?
The lists are in the "not beautiful listing" format to make the lists smaller and easier/better to diff (one line per sound entry vs multi-line formatting mess). Plus, if some people run it with -b and some people run it without -b, the list formats will vary wildly and eventually this would introduce confusion, possibly.

**Comment by zxz41** [comment]
The main reason was for generating listing for send listing (HL2, TF2 etc. Unfortunately have to be done in a hacky way). And I thought there was some way of making it detect that if the listing was already generated as "standard/beautiful" it would simply just leave it in that format. But don't really matter since I can already see why some people would easily get confused :x
